FOOD_THRESHOLD = 5
FOOD_SAFE_THRESHOLD = 20
INVENTORY_CHECK_INTERVAL = 10
MAX_STEPS_WITHOUT_FOOD = 10
EXPLORATION_TURN_INTERVAL = 5
COORDINATION_MAX_WAIT_STEPS = 40
COORDINATION_REBROADCAST_STEPS = 5
